package com.yannitech.state.model;

public enum OrderEvents {

	PLACE_ODRER,MAKE_PRODUCTION,PRODUCE,
	PRODUCTION,STOCK,ODER,FILLING,
	SENDING,SENT,TIMER,SENT_REMINDER,
	RECIEVE_PAYMENT,HANDLING,NOTIFICATION,
	NOFIED,PRODUCT_ORDER,ORDER_SHIPPED, REJCET_ODER,
	APPROVED_ODER,PREPERING_STOCK,PREPARE_BILL;
	
}
